Feature/add tekton pipelines (#23)
* refactor(apps/staging/tekton/): deploy components with operator

Why: operator make the deployment simpler
Ref: https://tekton.dev/docs/operator

* feat(apps/staging/tekton): add tasks and pipelines

* refactor(apps/staging/tekton): using flux kustomize to make config depend on setup

* feat(apps/staging/tekton): setup ingress host and path configurable from secret

* fix(apps/staging/tekton): add namespace before setup with `TektonConfig`

* feat(apps/staging/tekton): upgrade tekton with force stragery

* feat(apps/staging/tekton): add wait timeout for setup

* feat(apps/staging/tekton): add items for health checking

* fix(apps/staging/tekton): configs kustomization path

* fix(apps/staging/tekton/setup): ingress for https after nginx with ssl terminator

* fix(apps/staging/tekton/config): namespace yaml

* docs(charts/prow): add doc for plugin updating

* feat(apps/staging/prow): add prow global config and plugins config

* ci(gitops): make more stable

* feat(apps/staging/prow): add prow global config and plugins config

* fix(apps/staging/tekton): try to fix ci failure

Error: `Ingress/tekton-pipelines/tekton-dashboard immutable field detected, failed to delete object, error: ingresses.networking.k8s.io "tekton-dashboard" not found`

* fix(apps/staging/tekton): try to fix ci failure

error:
```bash
Ingress/tekton-pipelines/tekton-dashboard dry-run failed, reason: Invalid, error: Ingress.extensions "tekton-dashboard" is invalid: [spec.rules[0].host: Invalid value: "${domain}": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.rules[0].http.paths[0].path: Invalid value: "${path_for_dashboard}(/|$)(.*)": must be an absolute path]
```